#!/usr/bin/env bash
set -euo pipefail

# Copies one already-validated Arclume Runtime release into the App bundle
# resources. Wine is never built in this repository; see Arclume-Runtime.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DESTINATION_DIR="$ROOT_DIR/Procyon/Resources/OnlineGameDependencies"

archive=""
manifest=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --archive)
      shift
      archive="${1:-}"
      ;;
    --manifest)
      shift
      manifest="${1:-}"
      ;;
    --help|-h)
      cat <<'USAGE'
Usage: ./script/embed_runtime_release.sh --archive PATH --manifest PATH

Stages a release generated by the private Arclume-Runtime repository into this
App checkout. It verifies the release manifest and SHA-256 before copying.
The command does not delete a previous archive; remove a superseded resource
in a separate, reviewed App commit.
USAGE
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
  shift
done

if [[ -z "$archive" || -z "$manifest" ]]; then
  echo "--archive and --manifest are required." >&2
  exit 2
fi
if [[ ! -f "$archive" || ! -f "$manifest" ]]; then
  echo "Release archive or manifest is missing." >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required to validate the runtime manifest." >&2
  exit 1
fi

runtime_id="$(jq -r '.id // empty' "$manifest")"
archive_name="$(jq -r '.archive.name // empty' "$manifest")"
expected_sha="$(jq -r '.archive.sha256 // empty' "$manifest")"
if [[ "$runtime_id" != "io.arclume.runtime.wine" ||
      ! "$archive_name" =~ ^[A-Za-z0-9._-]+$ ||
      ! "$expected_sha" =~ ^[a-f0-9]{64}$ ]]; then
  echo "Runtime manifest does not satisfy the App contract." >&2
  exit 1
fi
if [[ "$(basename "$archive")" != "$archive_name" ]]; then
  echo "Archive name does not match the manifest." >&2
  exit 1
fi

actual_sha="$(/usr/bin/shasum -a 256 "$archive" | /usr/bin/awk '{print $1}')"
if [[ "$actual_sha" != "$expected_sha" ]]; then
  echo "Archive SHA-256 does not match the manifest." >&2
  exit 1
fi

/bin/mkdir -p "$DESTINATION_DIR"
/bin/cp "$archive" "$DESTINATION_DIR/$archive_name"
/bin/cp "$manifest" "$DESTINATION_DIR/arclume-wine-runtime.json"
echo "Embedded ${archive_name} (${actual_sha})"
